app/models/conference.rb, app/models/user.rb, app/models/vice.rb, config/routes.rb
Hey, I've added routes and created models. Please check it out and push it to master
=> Add routes

app/controllers/vices_controller.rb, app/models/user.rb, app/models/vice.rb, app/views/vices/index.html.erb, app/views/vices/show.html.erb, test/controllers/vices_controller_test.rb
Hey guy, I've added controller and views for vices. Please check it out and merge it to master!
=> controller vice + views sans mise en forme

app/views/devise/registrations/new.html.erb
il manque dans le controller user d'enregistrer les prenom et nom 
( heriter un controller ? en recherhce ? )
=> User amelioration

app/controllers/vices_controller.rb, app/views/vices/index.html.erb, app/views/vices/new.html.erb, app/views/vices/show.html.erb, config/routes.rb
vice sans le lien avec user-id
=> pas le lien avec les user mais globalement vice marche

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/vices/index.html.erb
juste un changement de couleur de bordure
=> Initialize bootstrap theme

app/controllers/application_controller.rb, app/controllers/conferences_controller.rb, app/controllers/vices_controller.rb, app/views/vices/index.html.erb
first et last name dans la création d'un nouvel user
authorisaiton de se balader sans login dans index show des vices
authorisation de new ( MAIS PAS DE CREER ) une conference sans identification
@marceau21
=> First last name et authorisation et authorisation

app/controllers/conferences_controller.rb, app/models/conference.rb, app/views/conferences/index.html.erb, app/views/shared/_navbar.html.erb, app/views/vices/show.html.erb, config/routes.rb
Hey guys!
Index et show pour les confs
=> conference index controller routes

app/controllers/conferences_controller.rb, app/controllers/vices_controller.rb, app/views/conferences/new.html.erb, app/views/vices/new.html.erb
creation vice et conf marche !
=> implementation de user  dans conf et vice creatino

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/users_controller.rb, app/controllers/vices_controller.rb, app/views/conferences/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, app/views/vices/index.html.erb, app/views/vices/new.html.erb, app/views/vices/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
=> Users controller

app/controllers/conferences_controller.rb, app/controllers/vices_controller.rb, db/migrate/20200218131031_remove_disponibility_column.rb, db/migrate/20200218131238_add_starting_date_and_ending_date.rb, db/schema.rb
=> ajout de la starting date et ending date dans Vice

app/views/vices/new.html.erb
=> bug disponibility simple form fixed

app/controllers/application_controller.rb, app/controllers/vices_controller.rb, app/models/user.rb, app/models/vice.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/vices/new.html.erb, app/views/vices/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20200218141044_create_active_storage_tables.active_storage.rb, db/schema.rb
=> ajout du cloudinary setup

app/views/shared/_card.html.erb, db/migrate/20200218141553_create_active_storage_tables.active_storage.rb
Add new components cards to copy if needed
=> Add cards components

app/assets/stylesheets/pages/_index.scss, app/views/vices/index.html.erb
juste une modif pour rétablir le wrapper des cards
=> home_page in progress

app/views/shared/_card.html.erb
ppour avoir une jolie carte à la bonne width
=> correct width card

app/views/users/index.html.erb, app/views/users/show.html.erb
if ajouté sur show et index user mais pas sur les card vice
=> ajout du if sur user show et index

db/seeds.rb
=> Seed launching on Vices & Users

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_index.scss, app/views/conferences/index.html.erb, app/views/conferences/show.html.erb, app/views/vices/index.html.erb, app/views/vices/show.html.erb, db/seeds.rb
=> Conferences show

app/assets/stylesheets/components/_inputfile.scss, app/views/devise/registrations/_new.html.erb, app/views/vices/_new.html.erb
suppression du JS => formulaires users et vice ok
=> suppression du JS sur les bouton de form

app/views/vices/index.html.erb
=> page index bug fixed

app/controllers/conferences_controller.rb, app/views/conferences/index.html.erb, app/views/conferences/new.html.erb, app/views/conferences/show.html.erb, db/migrate/20200219162922_remove_column_title_from_conference.rb, db/schema.rb
=> remove title

app/views/conferences/index.html.erb, app/views/vices/index.html.erb
=> routes dans index + condition si empty

app/controllers/vices_controller.rb, app/views/users/index.html.erb, app/views/vices/index.html.erb
Oulalalalala c'est bon ça bébé
=> Vice index filter

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/controllers/vices_controller.rb, app/models/user.rb, app/models/vice.rb, app/views/users/index.html.erb, app/views/vices/index.html.erb
=> pagination on users and vices done

app/views/users/index.html.erb
=> Display categories on user

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/pages/confirmation.html.erb
=> log in and sign up page done
